### PR TITLE
Upgrading psycopg2 to fix Error: could not determine PostgreSQL version from '11.5'

### PR DESCRIPTION
**Pull request by dkayiwa**
https://ci.openmrs.org/browse/OCL-OWD-55/log

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rkorytkowski do you wanna merge this? 😊

**Comment by rkorytkowski** [comment]
Have you verified that the app fires up and doesn't throw errors?

**Comment by dkayiwa** [comment]
No i have not.

**Comment by rkorytkowski** [comment]
Fixed, thanks Daniel!

**Pull request closed without merging**
